### ISSUE TITLE
Are there any docs about the methodology on how ref. ranges are extracted?

### ISSUE THREAD

**Issue by matentzn** [caufieldjh/brrr#3]
Are you using any external sources? Can this be kept up to date, or is this essentially manually curated?

**Comment by caufieldjh** [comment]
The good news is that all the sources are listed here: https://github.com/caufieldjh/brrr/blob/master/sources.tsv

The bad news is that most of the entries have to be manually curated as the sources are loosely structured.

**Comment by caufieldjh** [comment]
And, naturally, one of the sources recently went ~~private~~: https://www.aacc.org/advocacy-and-outreach/lab-tests-online
OK,[ not private](https://www.testing.com/), just less scrapable.

**Comment by matentzn** [comment]
Sweet thank you!
